name: ci/cd
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 619705995164.dkr.ecr.us-east-1.amazonaws.com/introspection-api:latest
