name: AWS App Runner
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  cd:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::619705995164:role/github-actions-deploy

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 619705995164.dkr.ecr.us-east-1.amazonaws.com/introspection-api:latest
